# Importing libaries

In [110]:
import arlpy.uwapm as pm
import arlpy.plot as plt
import numpy as np

 # Load bellhop model

In [111]:
pm.models()

['bellhop']

# Creating an environmental file i.e default

In [126]:
env = pm.create_env2d()
pm.print_env(env)

                name : arlpy
   bottom_absorption : 0.1
      bottom_density : 1600
    bottom_roughness : 0
   bottom_soundspeed : 1600
               depth : 25
        depth_interp : linear
           frequency : 25000
           max_angle : 80
           min_angle : -80
              nbeams : 0
            rx_depth : 10
            rx_range : 1000
          soundspeed : 1500
   soundspeed_interp : spline
             surface : None
      surface_interp : linear
            tx_depth : 5
   tx_directionality : None
                type : 2D


# Ploting the design environment

In [127]:
pm.plot_env(env, width=900)

# Compute arrivals using bellhop ray model

In [128]:
arrivals = pm.compute_arrivals(env)
pm.plot_arrivals(arrivals, width=900)

# Convert arrivals into impulse response

In [129]:
ir = pm.arrivals_to_impulse_response(arrivals, fs=96000)
plt.plot(np.abs(ir), fs=96000, width=900)

# Save CIR into CSV File i.e impulse_response.csv

In [8]:
ir = pm.arrivals_to_impulse_response(arrivals, fs=96000)
np.savetxt("impulse_response.csv", ir, delimiter=",")

# Setting up another environment paramaters as follow

In [128]:
bathy = [
    [0, 30],    # 30 m water depth at the transmitter
    [300, 20],  # 20 m water depth 300 m away
    [1000, 25]  # 25 m water depth at 1 km
]

In [304]:
print(bathy)

[[0, 3000], [500, 3000], [700, 500], [800, 3000], [1100, 3000]]


In [306]:
ssp = [
    [ 0, 1540],  # 1540 m/s at the surface
    [10, 1530],  # 1530 m/s at 10 m depth
    [20, 1532],  # 1532 m/s at 20 m depth
    [25, 1533],  # 1533 m/s at 25 m depth
    [30, 1535]   # 1535 m/s at the seabed
]

In [307]:
print(ssp)

[[0, 1540], [10, 1530], [20, 1532], [25, 1533], [30, 1535]]


# New environment name = env1

In [130]:
env1 = pm.create_env2d(
    depth=bathy,
    soundspeed=ssp,
    bottom_soundspeed=1450,
    bottom_density=1200,
    bottom_absorption=1.0,
    tx_depth=15
)

# Ploting/printing new env

In [131]:
pm.print_env(env1)

                name : arlpy
   bottom_absorption : 1.0
      bottom_density : 1200
    bottom_roughness : 0
   bottom_soundspeed : 1450
               depth : [[   0.   30.]
                        [ 300.   20.]
                        [1000.   25.]]
        depth_interp : linear
           frequency : 25000
           max_angle : 80
           min_angle : -80
              nbeams : 0
            rx_depth : 10
            rx_range : 1000
          soundspeed : [[   0. 1540.]
                        [  10. 1530.]
                        [  20. 1532.]
                        [  25. 1533.]
                        [  30. 1535.]]
   soundspeed_interp : spline
             surface : None
      surface_interp : linear
            tx_depth : 15
   tx_directionality : None
                type : 2D


In [132]:
pm.plot_env(env1, width=900)

# Compute arrivals of new environment i.e env1 and plot it

In [133]:
arrivals1 = pm.compute_arrivals(env1)
pm.plot_arrivals(arrivals1, width=900)

# Convert new arrivals into Impulse response (ir1) and plot it

In [90]:
ir1 = pm.arrivals_to_impulse_response(arrivals1, fs=96000)
plt.plot(np.abs(ir1), fs=96000, width=900)

# Save to CSV i.e impulse_response1.csv

In [134]:
ir1 = pm.arrivals_to_impulse_response(arrivals1, fs=96000)
np.savetxt("impulse_response1.csv", ir1, delimiter=",")

# Generating another environment

In [309]:
bathy = [
    [0, 30],    # 50 m water depth at the transmitter
    [500, 28],  # 28 m water depth 500 m away
    [1000, 25]  # 25 m water depth at 1 km
]

In [310]:
print(bathy)

[[0, 30], [500, 28], [1000, 25]]


In [151]:
ssp = [
    [ 0, 1540],  # 1540 m/s at the surface
    [10, 1530],  # 1530 m/s at 10 m depth
    [20, 1532],  # 1532 m/s at 20 m depth
    [25, 1533],  # 1533 m/s at 25 m depth
    [30, 1535]   # 1535 m/s at the seabed
]

In [311]:
print(ssp)

[[0, 1540], [10, 1530], [20, 1532], [25, 1533], [30, 1535]]


In [152]:
env3 = pm.create_env2d(
    depth=bathy,
    soundspeed=ssp,
    bottom_soundspeed=1450,
    bottom_density=1250,
    bottom_absorption=1.0,
    tx_depth=10
)

In [153]:
pm.print_env(env3)

                name : arlpy
   bottom_absorption : 1.0
      bottom_density : 1250
    bottom_roughness : 0
   bottom_soundspeed : 1450
               depth : [[   0.   30.]
                        [ 500.   28.]
                        [1000.   25.]]
        depth_interp : linear
           frequency : 25000
           max_angle : 80
           min_angle : -80
              nbeams : 0
            rx_depth : 10
            rx_range : 1000
          soundspeed : [[   0. 1540.]
                        [  10. 1530.]
                        [  20. 1532.]
                        [  25. 1533.]
                        [  30. 1535.]]
   soundspeed_interp : spline
             surface : None
      surface_interp : linear
            tx_depth : 10
   tx_directionality : None
                type : 2D


In [313]:
pm.plot_env(env3, width=900)

In [155]:
arrivals3 = pm.compute_arrivals(env3)
pm.plot_arrivals(arrivals3, width=900)

In [156]:
ir3 = pm.arrivals_to_impulse_response(arrivals3, fs=96000)
plt.plot(np.abs(ir3), fs=96000, width=900)

In [157]:
np.savetxt("impulse_response3.csv", ir3, delimiter=",")

# Generating another environment

In [159]:
depths = np.arange(0, 100, 5)    # Depths in meters
soundspeeds = np.random.normal(1500, 50, len(depths))  # Sound speeds in m/s

In [169]:
print(depths)

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [171]:
print(soundspeeds )

[1533.87002399 1499.22159239 1432.84965863 1480.31166885 1490.6481365
 1523.1525141  1579.35188    1568.36382175 1528.85203536 1494.76776543
 1494.29174108 1454.78963948 1502.89258116 1550.40570124 1475.30607571
 1482.5712993  1552.88039201 1540.71711786 1581.40715294 1572.42133797]


In [160]:
bathy = np.zeros((20, 2))
for i in range(20):
    bathy[i, 0] = i * 100  # Distance in meters
    bathy[i, 1] = np.random.uniform(5, 100)  # Depth in meters


In [167]:
print(bathy)

[[   0.           34.57506723]
 [ 100.           64.35204158]
 [ 200.           17.70531533]
 [ 300.           11.45956183]
 [ 400.           60.55889934]
 [ 500.           43.51983141]
 [ 600.           12.69742471]
 [ 700.           83.98330169]
 [ 800.           76.10087153]
 [ 900.           29.86196237]
 [1000.           40.00612832]
 [1100.           60.91658976]
 [1200.           26.89253997]
 [1300.           86.7597453 ]
 [1400.           91.69802496]
 [1500.           83.94685853]
 [1600.           67.68373948]
 [1700.           80.97314941]
 [1800.           54.74342747]
 [1900.           75.81125519]]


In [172]:
env4 = pm.create_env2d(depth=bathy, soundspeed=list(zip(depths, soundspeeds)), tx_depth=10,rx_depth=15)

In [312]:
env4

{'name': 'arlpy',
 'type': '2D',
 'frequency': 25000,
 'soundspeed': array([[   0.        , 1533.87002399],
        [   5.        , 1499.22159239],
        [  10.        , 1432.84965863],
        [  15.        , 1480.31166885],
        [  20.        , 1490.6481365 ],
        [  25.        , 1523.1525141 ],
        [  30.        , 1579.35188   ],
        [  35.        , 1568.36382175],
        [  40.        , 1528.85203536],
        [  45.        , 1494.76776543],
        [  50.        , 1494.29174108],
        [  55.        , 1454.78963948],
        [  60.        , 1502.89258116],
        [  65.        , 1550.40570124],
        [  70.        , 1475.30607571],
        [  75.        , 1482.5712993 ],
        [  80.        , 1552.88039201],
        [  85.        , 1540.71711786],
        [  90.        , 1581.40715294],
        [  91.69802496, 1593.3026958 ]]),
 'soundspeed_interp': 'spline',
 'bottom_soundspeed': 1600,
 'bottom_density': 1600,
 'bottom_absorption': 0.1,
 'bottom_roughness

In [173]:
pm.plot_env(env4)

In [164]:
arrivals4 = pm.compute_arrivals(env4)
pm.plot_arrivals(arrivals4, width=900)

In [165]:
ir4 = pm.arrivals_to_impulse_response(arrivals4, fs=96000)
plt.plot(np.abs(ir4), fs=96000, width=900)

In [166]:
np.savetxt("impulse_response4.csv", ir4, delimiter=",")

# Generating another environment

In [5]:
import numpy as np
depths = np.arange(0, 70, 5)    # Depths in meters
soundspeeds = np.random.normal(1500, 50, len(depths))  # Sound speeds in m/s 

# Generate a random bathymetry
bathy = np.zeros((15, 2))
for i in range(15):
    bathy[i, 0] = i * 100  # Distance in meters
    bathy[i, 1] = np.random.uniform(5, 60)  # Depth in meters


In [6]:
print(depths)

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65]


In [7]:
print(soundspeeds)

[1496.35443444 1507.2798648  1507.55779048 1535.43239958 1542.93704538
 1517.59931904 1523.38354915 1509.34073108 1566.97074467 1477.41532851
 1480.5211612  1466.47401428 1493.2967658  1560.14881595]


In [8]:
print(bathy)

[[   0.           42.96935885]
 [ 100.           51.29513991]
 [ 200.           25.38954082]
 [ 300.           50.64700681]
 [ 400.           21.97533825]
 [ 500.           41.14499629]
 [ 600.           12.52349308]
 [ 700.           58.95291079]
 [ 800.           18.16786121]
 [ 900.           23.52171622]
 [1000.           37.08923334]
 [1100.           22.70071524]
 [1200.           35.2240147 ]
 [1300.           40.65732825]
 [1400.           36.20471021]]


In [10]:
import arlpy.uwapm as pm
import arlpy.plot as plt
import numpy as np
env5 = pm.create_env2d(depth=bathy, soundspeed=list(zip(depths, soundspeeds)), tx_depth=10,rx_depth=15)

In [314]:
env5

{'name': 'arlpy',
 'type': '2D',
 'frequency': 25000,
 'soundspeed': array([[   0.        , 1540.40392017],
        [   5.        , 1475.01690059],
        [  10.        , 1594.89943348],
        [  15.        , 1562.26636669],
        [  20.        , 1546.67473042],
        [  25.        , 1550.50524404],
        [  30.        , 1486.44717314],
        [  35.        , 1440.53584999],
        [  40.        , 1438.28297707],
        [  45.        , 1420.17556933],
        [  50.        , 1563.6489334 ],
        [  55.        , 1568.12002489],
        [  56.1770504 , 1559.01507327]]),
 'soundspeed_interp': 'spline',
 'bottom_soundspeed': 1600,
 'bottom_density': 1600,
 'bottom_absorption': 0.1,
 'bottom_roughness': 0,
 'surface': None,
 'surface_interp': 'linear',
 'tx_depth': 10,
 'tx_directionality': None,
 'rx_depth': 15,
 'rx_range': 1000,
 'depth': array([[   0.        ,   29.01844393],
        [ 100.        ,   33.09803553],
        [ 200.        ,   26.66792653],
        [ 300.   

In [11]:
# Plot the environment
pm.plot_env(env5)

In [12]:
pm.plot_ssp(env5)

In [13]:
# Compute the arrivals
arrivals5 = pm.compute_arrivals(env5)

In [14]:
# Plot the arrivals
pm.plot_arrivals(arrivals5)

In [15]:
# Convert the arrivals to impulse response
ir5 = pm.arrivals_to_impulse_response(arrivals5, fs=96000)

In [16]:
# Plot the impulse response
plt.plot(np.abs(ir5), fs=96000)

In [212]:
np.savetxt("impulse_response5.csv", ir5, delimiter=",")

# Generating another environment

In [17]:
depths = np.arange(0, 80, 5)    # Depths in meters
soundspeeds = np.random.normal(1450, 50, len(depths))  # Sound speeds in m/s 

# Generate a random bathymetry
bathy = np.zeros((15, 2))
for i in range(15):
    bathy[i, 0] = i * 100  # Distance in meters
    bathy[i, 1] = np.random.uniform(5, 60)  # Depth in meters

In [18]:
print(depths)

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75]


In [19]:
print(soundspeeds)

[1514.82965892 1458.83454571 1458.74259453 1404.57887603 1464.09121705
 1535.12368151 1484.66895174 1408.96435355 1554.56926569 1527.74958138
 1440.61877075 1463.89800851 1457.46967215 1467.67803617 1456.80020824
 1443.43625426]


In [20]:
print(bathy)

[[   0.           30.0943434 ]
 [ 100.           54.19783462]
 [ 200.           14.83005496]
 [ 300.            6.96940164]
 [ 400.           57.5278325 ]
 [ 500.           15.58012579]
 [ 600.            9.96701801]
 [ 700.           23.51282517]
 [ 800.           33.83034151]
 [ 900.            9.99217085]
 [1000.           56.08300292]
 [1100.           54.54508229]
 [1200.           15.70359308]
 [1300.           49.90193007]
 [1400.           52.6298872 ]]


In [21]:
env6 = pm.create_env2d(depth=bathy, soundspeed=list(zip(depths, soundspeeds)), tx_depth=10,rx_depth=15,rx_range=850
)
env6

{'name': 'arlpy',
 'type': '2D',
 'frequency': 25000,
 'soundspeed': array([[   0.        , 1514.82965892],
        [   5.        , 1458.83454571],
        [  10.        , 1458.74259453],
        [  15.        , 1404.57887603],
        [  20.        , 1464.09121705],
        [  25.        , 1535.12368151],
        [  30.        , 1484.66895174],
        [  35.        , 1408.96435355],
        [  40.        , 1554.56926569],
        [  45.        , 1527.74958138],
        [  50.        , 1440.61877075],
        [  55.        , 1463.89800851],
        [  57.5278325 , 1463.58316564]]),
 'soundspeed_interp': 'spline',
 'bottom_soundspeed': 1600,
 'bottom_density': 1600,
 'bottom_absorption': 0.1,
 'bottom_roughness': 0,
 'surface': None,
 'surface_interp': 'linear',
 'tx_depth': 10,
 'tx_directionality': None,
 'rx_depth': 15,
 'rx_range': 850,
 'depth': array([[   0.        ,   30.0943434 ],
        [ 100.        ,   54.19783462],
        [ 200.        ,   14.83005496],
        [ 300.    

In [22]:
# Plot the environment
pm.plot_env(env6)

In [23]:
# Compute the arrivals
arrivals6 = pm.compute_arrivals(env6)

In [24]:
# Plot the arrivals
pm.plot_arrivals(arrivals6)

In [257]:
# Convert the arrivals to impulse response
ir6 = pm.arrivals_to_impulse_response(arrivals6, fs=96000)

In [258]:
# Plot the impulse response
plt.plot(np.abs(ir6), fs=96000)

In [25]:
pm.plot_ssp(env6)

In [260]:
np.savetxt("impulse_response6.csv", ir6, delimiter=",")

# Generating another environment

In [112]:
depths = np.arange(0, 75, 5)    # Depths in meters

In [113]:
print(depths)

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70]


In [114]:
# Generate a random bathymetry
bathy = np.zeros((15, 2))
for i in range(15):
    bathy[i, 0] = i * 100  # Distance in meters
    bathy[i, 1] = np.random.uniform(5, 60)  # Depth in meters

In [117]:
print(bathy)

[[   0.            9.53095751]
 [ 100.           42.42746161]
 [ 200.           40.99811679]
 [ 300.           20.02927398]
 [ 400.           57.29749592]
 [ 500.           13.30818405]
 [ 600.           28.77841406]
 [ 700.           56.89887561]
 [ 800.           28.08500243]
 [ 900.           40.11892712]
 [1000.           26.86769189]
 [1100.           20.08183613]
 [1200.           59.11877064]
 [1300.           27.51337035]
 [1400.           54.1754562 ]]


In [116]:
soundspeeds = np.random.normal(1500, 50, len(depths))  # Sound speeds in m/s

In [31]:
print(soundspeeds)

[1446.93633636 1474.25300619 1494.23181192 1476.19902661 1466.69154799
 1475.04492019 1536.57964856 1458.47294355 1456.02389494 1511.15281396
 1534.37009754 1486.41660309 1495.12010351 1578.21091493 1587.01115377]


In [118]:
env7 = pm.create_env2d(depth=bathy, soundspeed=list(zip(depths, soundspeeds)), tx_depth=15,rx_depth=20,rx_range=850
)
env7

{'name': 'arlpy',
 'type': '2D',
 'frequency': 25000,
 'soundspeed': array([[   0.        , 1535.41782236],
        [   5.        , 1464.45640348],
        [  10.        , 1466.54394594],
        [  15.        , 1503.71031069],
        [  20.        , 1488.52986986],
        [  25.        , 1547.52513776],
        [  30.        , 1482.85120858],
        [  35.        , 1525.27509053],
        [  40.        , 1498.55375579],
        [  45.        , 1513.48346787],
        [  50.        , 1488.49717822],
        [  55.        , 1535.38577706],
        [  59.11877064, 1539.10232846]]),
 'soundspeed_interp': 'spline',
 'bottom_soundspeed': 1600,
 'bottom_density': 1600,
 'bottom_absorption': 0.1,
 'bottom_roughness': 0,
 'surface': None,
 'surface_interp': 'linear',
 'tx_depth': 15,
 'tx_directionality': None,
 'rx_depth': 20,
 'rx_range': 850,
 'depth': array([[   0.        ,    9.53095751],
        [ 100.        ,   42.42746161],
        [ 200.        ,   40.99811679],
        [ 300.    

In [120]:
pm.plot_env(env7)

In [123]:
arrivals7

tx_depth_ndx  rx_depth_ndx  rx_range_ndx  tx_depth  rx_depth  rx_range  \
1              0             0             0      15.0      20.0     850.0   
2              0             0             0      15.0      20.0     850.0   
3              0             0             0      15.0      20.0     850.0   
4              0             0             0      15.0      20.0     850.0   
5              0             0             0      15.0      20.0     850.0   
..           ...           ...           ...       ...       ...       ...   
60             0             0             0      15.0      20.0     850.0   
61             0             0             0      15.0      20.0     850.0   
62             0             0             0      15.0      20.0     850.0   
63             0             0             0      15.0      20.0     850.0   
64             0             0             0      15.0      20.0     850.0   

    arrival_number   arrival_amplitude  time_of_arrival  angle_of_departure  \
1                0  0.000113-0.000212j         0.579620          -24.435154   
2                1  0.000076+0.000441j         0.575372          -23.440809   
3                2 -0.000027+0.000036j         0.575371          -23.403154   
4                3 -0.000058+0.000223j         0.580428          -21.445045   
5                4 -0.000028+0.000006j         0.580427          -21.407391   
..             ...                 ...              ...                 ...   
60              59  0.000024+0.000030j         0.589233           25.963757   
61              60 -0.000006-0.000001j         0.589107           27.093433   
62              61 -0.000057+0.000017j         0.589107           27.131090   
63              62  0.000003-0.000001j         0.603430           28.712639   
64              63  0.000006-0.000005j         0.603430           28.750294   

    angle_of_arrival  surface_bounces  bottom_bounces  
1         -25.707466                4               4  
2          10.487248                4               3  
3          10.315132                4               3  
4         -32.326855                4               4  
5         -32.334854                4               4  
..               ...              ...             ...  
60        -27.259392                4               5  
61         -5.789631                4               5  
62         -5.693630                4               5  
63        -11.534242                5               6  
64        -11.452670                5               6  

[64 rows x 13 columns]

In [124]:
pm.plot_arrivals(arrivals7)

In [38]:
# Convert the arrivals to impulse response
ir7 = pm.arrivals_to_impulse_response(arrivals7, fs=96000)

In [39]:
ir7

array([-5.63239047e-05-5.27084177e-05j,  0.00000000e+00+0.00000000e+00j,
        0.00000000e+00+0.00000000e+00j, ...,
        0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j,
        5.97092067e-08+8.19160849e-08j])

In [40]:
# Convert the arrivals to impulse response
ir7 = pm.arrivals_to_impulse_response(arrivals7, fs=96000)

In [41]:
# Plot the impulse response
plt.plot(np.abs(ir7), fs=96000)

In [301]:
np.savetxt("impulse_response7.csv", ir7, delimiter=",")

In [125]:
pm.plot_ssp(env7)

In [2]:
import arlpy
arlpy.uwa.soundspeed()


1539.0866009307247

In [3]:
arlpy.uwa.soundspeed(temperature=25, depth=20)

1534.62044185722

In [108]:
rays = pm.compute_eigenrays(env7)
pm.plot_rays(rays, env=env7, width=900)

In [109]:
arrivals = pm.compute_arrivals(env7)
pm.plot_arrivals(arrivals, dB=True, width=900)